
plugin_repo(
  name = "cc",
  revision = "v0.3.2",
  plugin = "cc-rules",
  owner = "please-build",
)

plugin_repo(
  name = "cmake",
  revision = "master",
  plugin = "cmake-rules",
  owner = "cemeceme"
)