

filegroup(
 name = "catch2",
 srcs = ["catch2.build_defs"],
 visibility = ["PUBLIC"]
)

github_repo(
  name = "catch2-repo",
  repo = "catchorg/Catch2",
  revision = "v3.8.1",
  build_file = "BUILD.catch2",
  strip_build = True
)